### ISSUE TITLE
Should an error be thrown if FindOne doesn't return a record?

### ISSUE THREAD

**Issue by steebchen** [prisma/photongo#36]
Prisma used to throw an error in Photon.js when a FindOne call returns an error. Recently, this was reverted and Photon.js now returns a `null` object instead of throwing when no record was found. This was also [adapted in the internal query engine](https://github.com/prisma/prisma2/issues/914#issuecomment-556105293). Currently, Photon Go still returns an error, because Go lacks null types and this may be a better fit here. However, other approaches or suggestions are welcome.

Related issues for Photon.js:
- https://github.com/prisma/photonjs/issues/245
- https://github.com/prisma/photonjs/issues/89

This is how it works at the moment in Photon Go:

```go
user, err := client.User.FindOne(
  photon.User.ID.Equals("123"),
).Exec(ctx)

if err == photon.ErrNotFound {
  log.Printf("no record with id 123")
}
```

As an alternative, we could use a pointer to the result (`User`), and the user would have to check if it is nil before using it.

**Comment by robojones** [comment]
Returning an error would be analog to the behavior of the native SQL module in Go.

> If the query selects no rows, the *Row's Scan will return ErrNoRows.

https://godoc.org/database/sql#DB.QueryRow

**Comment by matthewmueller** [comment]
Vote for error as well, so you can do:

```go
if photon.IsNotFound(err) {
  // handle not found
} else if err != nil {
  // handle other errors
}
```
