### ISSUE TITLE
Strange Error ECONNRESET

### ISSUE THREAD

**Issue by zafhiel** [prisma/photongo#54]
Hi guys!

today i have a very strange error, look this schema.prisma.

```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

generator photon {
  provider = "/home/neo/golib/bin/photongo"
  output   = "./photon/photon_gen.go"
  package  = "photon"
}

model User {
    id       String   @default(cuid()) @id @unique
    name     Boolean
    password String
    rol      Rol[]
}

model Rol {
    id          String    @default(cuid()) @id @unique
    create      DateTime  @default(now())
    update      DateTime  @updatedAt
    name        String
    users       User[]
    permissions Permission[]
}

model Permission {
    id     String    @default(cuid()) @id @unique
    create DateTime  @default(now())
    key    String
    rol    Rol[]
}

```
Works very well, pass lift migrations without problems, generate the Photon Go client, but if you want add another field in any model for example in model **User** i just add the field **email** and looks like:

```prisma
model User {
    id       String   @default(cuid()) @id @unique
    name     Boolean
    password String
    email    String
    rol      Rol[]
}

```
:boom: i get this error:

```bash
go run github.com/prisma/photongo generate
> Downloading Prisma engines for debian-openssl-1.1.x [====================] 100%

Generating Photon Go to ./../photon.go
/__enclose_io_memfs__/build/index.js:217148
        throw ex;
        ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:610:25)
panic: could not run [generate]: exit status 7

goroutine 1 [running]:
main.main()
        /home/neo/golib/pkg/mod/github.com/prisma/photongo@v0.0.0-20191217175644-fc2a3926061a/main.go:19 +0x15a
exit status 2
```

Any ideas??? thanks! :hugs:

**Comment by steebchen** [comment]
That's indeed a strange error. Somehow I run into something similar locally, although not quite the same... I'll investigate more tomorrow.

**Comment by steebchen** [comment]
I got it! While the error message is slightly cryptic, it totally makes sense.

What happened is that Photon Go was invoked by the Prisma generator, but `bufio.Scanner` can't handle big payloads apparently. Also, I forgot to check if errors happened, because Go/my linters didn't force me to. Now, I'm using `bufio.Reader`, which doesn't have this restriction and also has proper error handling.

https://github.com/prisma/photongo/pull/56 will fix this.

**Comment by zafhiel** [comment]
Thanks!! I already tried it and works perfectly!! :smile:
