### ISSUE TITLE
Context passing

### ISSUE THREAD

**Issue by steebchen** [prisma/photongo#6]
Photon Go uses http calls for database requests. Depending on how a package can be used, a context should be passed to libraries and functions. The Go guidelines recommend that a context should be passed explicitly in server applications; although it's not quite clear how and when to do that.

Possible solutions:
- Provide a .WithContext method to optionally set a context.*
- Expose both .Exec() and .ExecContext(ctx) methods.*
- Make the context parameter configurable in the code generation options.
- Remove the context completely because it's mostly undefined behavior anyway. This would mean that we can't use chaining. 

This solution would allow using a combination of the two, which I don't like because people _will_ forget to set it in some part of the code if they want to use context.

Interesting facts:
- The http package allows setting the context optionally: `req.WithContext(ctx)`
- The Go blog says that "Go was designed for writing servers.", which would support setting the context explicitly https://blog.golang.org/go1.7-binary-size
- The database/sql packages provides function variations so the user can choose to use a context or not: Query and QueryContext.

Related discussions:
- [Go 2: simplify context handling](https://github.com/golang/go/issues/28342)

## Current view

Our current API spec uses chaining, which forces use to use a .Exec() method anyway. It would be simple to just add a context parameter `ctx` to this function. If users use photon in a non-http context, they can still just pass context.Background().

**Comment by darioielardi** [comment]
I think the current solution works well, a `ctx` param for the `.Exec()` method seems like a simple and idiomatic way to handle this and, as you said, it could always be provided with `context.Backgorund()`.

**Comment by steebchen** [comment]
This was an easy decision: it's pretty common to explicitly pass the context in Go, even if it's slightly verbose. It enables automatic request cancelling, and allows easy integration for tracing and logging. We plan to integrate context-related things like logging into Photon Go in the future.
